booking_system/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('',views.home, name='home'),
    path('accounts/signup/customer/', views.customerSignup, name='customer_register'),
    path('accounts/signup/accountant/', views.accountantSignup, name='accountant_register'),
    path('accounts/login/customer', views.customerLogin, name='customer_login'),
    path('accounts/login/accountant', views.accountantLogin, name='accountant_login'),
    path('accounts/logout/',views.logoutUser,name='logout'),
    path('customer/profile',views.customerProfile,name='customer_profile'),
    path('customer/home',views.customerHome,name='customer_home'),
    path('accountant/profile',views.accountantProfile,name='accountant_profile'),
    path('accountant/home',views.accountantHome,name='accountant_home')


  

]

digmak/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('booking_system.urls'))
]

booking_system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db.models.signals import post_save
# Create your models here.


class User(AbstractUser):
  USER_TYPE_CHOICES = (
      (1, 'customer'),
      (2, 'accountant'),
      (3, 'admin'),
  )

  user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES)
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O','Other')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    citizenship = models.CharField(max_length=30)
    country_residence = models.CharField(max_length=30)
 


class Accountant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O','Other')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    citizenship = models.CharField(max_length=30)
    country_residence = models.CharField(max_length=30)
    tax_regulation_specialty = models.CharField(max_length=50)
    hour_rate = models.DecimalField(decimal_places=2, max_digits=12,blank=True,null=True)
    availability = models.DateTimeField(auto_now=False, auto_now_add=False,blank=True,null=True)


def create_profile(sender,instance,created,**kwargs):
    if created and instance.user_type==1:
        Customer.objects.create(user=instance)
        print("customer profile created")
    elif created and instance.user_type == 2:
        Accountant.objects.create(user=instance)
        print("accountant profile created")
post_save.connect(create_profile,sender = User)

def update_profile(sender,instance,created,**kwargs):
    if created == False:
        print()
        try:
            if instance.user_type==1:
                instance.customer.save()
                print('profile updated')
            elif instance.user_type==2:
                instance.accountant.save()
        except:
            if instance.user_type==1:
                Customer.objects.create(user=instance)
                print('profile created for existing user')
            elif instance.user_type==2:
                Accountant.objects.create(user=instance)

post_save.connect(update_profile,sender = User)

booking_system/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from booking_system.models import Customer,Accountant,User
from .widgets import XDSoftDateTimePickerInput

class CustomerSignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get('email')

        try:
            match = User.objects.get(email = email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError('This email address is already in use.')


    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.user_type = 1
        user.save()
        
        return user

class AccountantSignupForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data.get('email')

        try:
            match = User.objects.get(email = email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError('This email address is already in use.')
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.user_type = 2
        user.save()
       
        return user

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

class AccountantForm(ModelForm):
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=XDSoftDateTimePickerInput())
    class Meta:
        model = Accountant
        fields = ['gender','citizenship','country_residence','tax_regulation_specialty','hour_rate','date']
        exclude = ['user']
    

booking_system/views.py
from django.shortcuts import render, redirect
from .forms import CustomerSignupForm,AccountantSignupForm, CustomerForm, AccountantForm
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Accountant, Customer

# Create your views here.
def home(request):
    if request.user.is_authenticated and request.user.user_type==1:
        return redirect('customer_home')
    elif request.user.is_authenticated and request.user.user_type==2:
        return redirect('accountant_home')
    return render(request,'home.html')


def accountantSignup(request):
    form = AccountantSignupForm()
    if request.method == "POST":
        form = AccountantSignupForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            return redirect('accountant_login')
    context = {'form':form}
    return render(request,'accountant/register.html',context)

def customerSignup(request):
    form = CustomerSignupForm()
    if request.method == "POST":
        form = CustomerSignupForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            return redirect('customer_login')
    context = {'form':form}
    return render(request,'customer/register.html',context)

def customerLogin(request):
    if request.method=="POST":
        customer_username = request.POST.get('username')
        customer_password = request.POST.get('password')
        user = authenticate(request,username=customer_username,password=customer_password)
        if user is not None:
            login(request,user)
            return redirect('customer_home')
        else:
            messages.info(request,"Incorrect UserName and Password")

    return render(request,'customer/login.html')

def accountantLogin(request):
    if request.method=="POST":
        accountant_username = request.POST.get('username')
        accountant_password = request.POST.get('password')
        user = authenticate(request,username=accountant_username,password=accountant_password)
        if user is not None:
            login(request,user)
            return redirect('accountant_home')
        else:
            messages.info(request,"Incorrect UserName and Password")

    return render(request,'accountant/login.html')

def logoutUser(request):
    logout(request)
    return redirect('home')

@login_required(login_url='accountant_login')
def accountantHome(request):
    if request.user.user_type==2:
        return render(request,'accountant/accountant_home.html')
    else:
        return redirect('home')

@login_required(login_url='customer_login')
def customerHome(request):
    if request.user.user_type==1:
        accountants = Accountant.objects.filter(hour_rate__isnull=False,user__username__isnull=False)
        context = {'accountants':accountants}
        return render(request,'customer/customer_home.html',context)
    else:
        return redirect('home')

@login_required(login_url='customer_login')
def customerProfile(request):
    if request.user.user_type==1:
        customer = request.user.customer
        form = CustomerForm(instance=customer)
        if request.method=="POST":
            form = CustomerForm(request.POST,request.FILES,instance=customer)
            if form.is_valid():
                form.save()
        context = {"form":form}
        return render(request,'customer/customer_profile.html',context)
    else:
        return redirect('home')

@login_required(login_url='accountant_login')
def accountantProfile(request):
    if request.user.user_type==2:
        accountant = request.user.accountant
        form = AccountantForm(instance=accountant)
        if request.method == "POST":
            form = AccountantForm(request.POST,request.FILES,instance=accountant)
            if form.is_valid():
                form.save()
        context = {"form":form}
        return render(request,'accountant/accountant_profile.html',context)
    else:
        return redirect('home')

booking_system/templates/auth_base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login_style.css'%}">
	<title>Digmak</title>

  </head>
  <body>

    {%block content%}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  </body>
</html>

booking_system/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
      <link
    rel="stylesheet"
    href="{% static 'css/all.min.css' %}"
  />
  <!-- Page CSS -->
  <link
    rel="stylesheet"
    href=" {% static 'css/fullcalendar.min.css'%}"
  />
  <link
    rel="stylesheet"
    href=" {% static 'css/sweetalert2.min.css'%}"
  />
  <!-- Purpose CSS -->
  <link rel="stylesheet" href="{%static 'css/purpose.css'%}" id="stylesheet" />
    <script src="{% static 'js/jquery.datetimepicker.full.min.js' %}"></script>
   
  </head>
  <body>
    
    {%block content%}

    {%endblock%}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script src="{%static 'js/purpose.core.js'%}"></script>
<!-- Page JS -->
<script src="{%static 'js/moment.min.js'%}"></script>
<script src=" {%static 'js/fullcalendar.min.js'%}"></script>
<script src=" {%static 'js/sweetalert2.min.js'%}"></script>
<!-- Purpose JS -->
<script src="{%static 'js/purpose.js'%}"></script>

    <script>
      $(function () {
    $("#id_date").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
    </script>
  </body>
</html>

booking_system/templates/home.html
{% extends 'base.html' %}
{%block content%}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Digmak</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
    <span class="navbar-text">
    <a href="{%url 'accountant_login'%}">
      Accountants
      </a>
    </span>
     <span class="navbar-text ml-2">
     <a href="{%url 'customer_login'%}">
      Customer
      </a>
      
    </span>
  </div>
</nav>
{%endblock%}